const mongoose=require("mongoose");
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true
    },
    password:{
        type:String,
        required:true,
        minlength:6
    },
    role:{
        type:String,
        enum:["admin","faculty","student"],
        required:true
    },
    department:{
        type:String,
        trim:true
    },
    semester:{
        type:Number
    },
    section:{
        type:String,
        trim:true
    },
    parentEmail:{
        type:String,
        trim:true,
        lowercase:true
    },
    employeeId:{
        type:String,
        trim:true,
    },
    studentId:{
        type:String,
        trim:true,
    }
},{timestamps:true});
module.exports=mongoose.model("User",userSchema);
